server:
    port: 9600
    servlet:
        context-path: /momentum
    compression:
        enabled: true
        mime-types: application/json
        min-response-size: 1024
    http2:
        enabled: true
spring:
    application:
        name: momentum
    mvc:
        throw-exception-if-n0-handler-found: true
    cloud:
        config:
            enabled: false
            import-check:
                enabled: false
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${postgres.service.host}:${postgres.service.port}/${database.name}
        platform: postgres
        username: ${postgres.service.username}
        password: ${postgres.service.password}
        hikari:
            connectionTimeout: 20000
            maxLifetime: 600000
            maximumPoolSize: 10
            schema: backend
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                lob:
                    non_contextual_creation: true
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true
    profiles:
        active: default

database:
    name: momentumdb
postgres:
    service:
        host: localhost
        password: admin
        port: 5432
        username: admin


springdoc:
    api-docs:
        enable: true
        path: /v3/api-docs
        swagger-ui:
            path: /swagger-ui.html
    version: 1.0
